### ISSUE TITLE
v4.2.3 启用报错 NullPointerException 的解决方法

### ISSUE THREAD

**Issue by troyzhxu** [troyzhxu/bean-searcher#80]
解决方法，添加配置：

```yml
bean-searcher:
  params:
    convertor:
      date-target: SQL_DATE
      date-time-target: SQL_TIMESTAMP
      time-target: SQL_TIME
```
