### ISSUE TITLE
多数据源时候的方言问题

### ISSUE THREAD

**Issue by ericqy197206** [troyzhxu/bean-searcher#84]
我有多个多数据源，而且是不同类型的，数据库方言不一样。每次查询都要指定Dialect，非常不便
既然SearchBean注解有了dataSource属性，能不能再加一个dialect属性？这样能少很多代码量

**Comment by troyzhxu** [comment]
可使用如下配置，为不同的数据源指定不同的方言：

```yml
bean-searcher:
    sql:
        dialect-dynamic: true
        dialects:
            dataSouseceName1:  MySQL
            dataSouseceName2:  Oracle
            dataSouseceName3:  PgSQL
            dataSouseceName4:  SqlServer
```
